### ISSUE TITLE
Relative links not working in footnotes

### ISSUE THREAD

**Issue by xuhcc** [benbalter/jekyll-relative-links#56]
### Describe the bug

Hi,

I'm using Github Pages service to generate a static website from a collection of markdown files.
Relative links in footnotes are not working as expected. They are rendered as links to markdown files, instead of links to html files.

**test1.md**

```markdown
TEST[^1].

[test2](test2.md).

[^1]: [test2](test2.md).
```

**test2.md**
```markdown
TEST
```

**_config.yml**:

```yaml
...
kramdown:
  gfm_quirks: [paragraph_end, no_auto_typographic]
...
```

### Expected behavior

Link in footnote should be rendered as `<a href="/test2.html">test2</a>`.

### Actual behavior

But it is rendered as `<a href="test2.md">test2</a>`.
